# Generated by Django 5.0.6 on 2024-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('basic', models.IntegerField(blank=True, null=True)),
                ('hra', models.IntegerField(blank=True, null=True)),
                ('desgn', models.CharField(blank=True, max_length=20, null=True)),
                ('dept', models.CharField(blank=True, max_length=15, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addr1', models.CharField(blank=True, max_length=20, null=True)),
                ('addr2', models.CharField(blank=True, max_length=20, null=True)),
                ('addr3', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('ph_no', models.IntegerField(blank=True, null=True)),
                ('rep_officer_no', models.CharField(blank=True, max_length=8, null=True)),
                ('rep_officer_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
    ]
