# Generated by Django 5.0.6 on 2024-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStore',
            fields=[
                ('file_number', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'media_store',
                'managed': True,
            },
        ),
    ]
