# Generated by Django 5.0.6 on 2024-05-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediastore',
            options={'managed': False},
        ),
    ]
