# Generated by Django 5.0.6 on 2024-05-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mediastore_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediastore',
            options={},
        ),
    ]
